// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetcorestore.Models;

namespace dotnetcorestore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190123142113_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dotnetcorestore.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Donator")
                        .IsRequired();

                    b.Property<int>("IdAssociation");

                    b.Property<int>("IdUtilisateur");

                    b.Property<float>("Montant");

                    b.Property<float>("MontantPourboire");

                    b.Property<string>("Statut");

                    b.HasKey("Id");

                    b.ToTable("Paiements");
                });
#pragma warning restore 612, 618
        }
    }
}
